-- MySQL Script generated by MySQL Workbench
-- Tue 07 Nov 2017 03:16:16 PM -02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd_enem_2015
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_enem_2015
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_enem_2015` DEFAULT CHARACTER SET utf8 ;
USE `bd_enem_2015` ;

-- -----------------------------------------------------
-- Table `bd_enem_2015`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_enem_2015`.`table1` (
)

-- -----------------------------------------------------
-- Table `bd_enem_2015`.`UnidadeFederativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_enem_2015`.`UnidadeFederativa` (
  `IdUF` INT NOT NULL,
  `SiglaUF` VARCHAR(45) NULL,
  PRIMARY KEY (`IdUF`))

-- -----------------------------------------------------
-- Table `bd_enem_2015`.`Municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_enem_2015`.`Municipio` (
  `IdMunic` INT NOT NULL,
  `NomeMunic` VARCHAR(45) NULL,
  PRIMARY KEY (`IdMunic`))

-- -----------------------------------------------------
-- Table `bd_enem_2015`.`Escola`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_enem_2015`.`Escola` (
  `IdEscola` INT NOT NULL,
  `TipoDependAdmin` VARCHAR(45) NULL,
  `TipoLocalizEscol` VARCHAR(45) NULL,
  `TipoSituFunc` VARCHAR(45) NULL,
  `Municipio_IdMunic` INT NOT NULL,
  `UnidadeFederativa_IdUF` INT NOT NULL,
  `Municipio_IdMunic1` INT NOT NULL,
  PRIMARY KEY (`IdEscola`),
  INDEX `fk_Escola_UnidadeFederativa1_idx` (`UnidadeFederativa_IdUF` ASC),
  INDEX `fk_Escola_Municipio1_idx` (`Municipio_IdMunic1` ASC),
  CONSTRAINT `fk_Escola_UnidadeFederativa1`
    FOREIGN KEY (`UnidadeFederativa_IdUF`)
    REFERENCES `bd_enem_2015`.`UnidadeFederativa` (`IdUF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Escola_Municipio1`
    FOREIGN KEY (`Municipio_IdMunic1`)
    REFERENCES `bd_enem_2015`.`Municipio` (`IdMunic`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)

-- -----------------------------------------------------
-- Table `bd_enem_2015`.`Candidato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_enem_2015`.`Candidato` (
  `IdCandidato` INT NOT NULL,
  `CorRaca` VARCHAR(45) NULL,
  `AnoConcluEM` DATETIME NULL,
  `EstadoCivil` VARCHAR(45) NULL,
  `Nacionalidade` VARCHAR(45) NULL,
  `TipoEscolaEM` VARCHAR(45) NULL,
  `SituacaoConcluEM` VARCHAR(45) NULL,
  `TipoDeEnsiEM` VARCHAR(45) NULL,
  `Sexo` VARCHAR(45) NULL,
  `Idade` INT NULL,
  `UnidadeFederativa_IdUF` INT NOT NULL,
  `UnidadeFederativa_IdUF1` INT NOT NULL,
  `Municipio_IdMunic` INT NOT NULL,
  `Escola_IdEscola` INT NOT NULL,
  PRIMARY KEY (`IdCandidato`),
  INDEX `fk_Candidato_UnidadeFederativa1_idx` (`UnidadeFederativa_IdUF1` ASC),
  INDEX `fk_Candidato_Municipio1_idx` (`Municipio_IdMunic` ASC),
  INDEX `fk_Candidato_Escola1_idx` (`Escola_IdEscola` ASC),
  CONSTRAINT `fk_Candidato_UnidadeFederativa1`
    FOREIGN KEY (`UnidadeFederativa_IdUF1`)
    REFERENCES `bd_enem_2015`.`UnidadeFederativa` (`IdUF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Candidato_Municipio1`
    FOREIGN KEY (`Municipio_IdMunic`)
    REFERENCES `bd_enem_2015`.`Municipio` (`IdMunic`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Candidato_Escola1`
    FOREIGN KEY (`Escola_IdEscola`)
    REFERENCES `bd_enem_2015`.`Escola` (`IdEscola`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)

-- -----------------------------------------------------
-- Table `bd_enem_2015`.`Redacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_enem_2015`.`Redacao` (
  `IdRedacao` INT NOT NULL,
  `Situacao` VARCHAR(45) NULL,
  `Nota` INT NULL,
  `Candidato_IdCandidato` INT NOT NULL,
  PRIMARY KEY (`IdRedacao`),
  INDEX `fk_Redacao_Candidato1_idx` (`Candidato_IdCandidato` ASC),
  CONSTRAINT `fk_Redacao_Candidato1`
    FOREIGN KEY (`Candidato_IdCandidato`)
    REFERENCES `bd_enem_2015`.`Candidato` (`IdCandidato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)

-- -----------------------------------------------------
-- Table `bd_enem_2015`.`NotaCompetencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_enem_2015`.`NotaCompetencia` (
  `IdNumComp` INT NOT NULL,
  `Nota` INT NULL,
  `Redacao_IdRedacao` INT NOT NULL,
  PRIMARY KEY (`IdNumComp`, `Redacao_IdRedacao`),
  INDEX `fk_NotaCompetencia_Redacao1_idx` (`Redacao_IdRedacao` ASC),
  CONSTRAINT `fk_NotaCompetencia_Redacao1`
    FOREIGN KEY (`Redacao_IdRedacao`)
    REFERENCES `bd_enem_2015`.`Redacao` (`IdRedacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)

-- -----------------------------------------------------
-- Table `bd_enem_2015`.`CertificadoEnsinoMedio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_enem_2015`.`CertificadoEnsinoMedio` (
  `IdCertificado` INT NOT NULL,
  `IndicSolicCertif` VARCHAR(45) NULL,
  `NomeEntCert` VARCHAR(45) NULL,
  `Candidato_IdCandidato` INT NOT NULL,
  PRIMARY KEY (`IdCertificado`),
  INDEX `fk_CertificadoEnsinoMedio_Candidato1_idx` (`Candidato_IdCandidato` ASC),
  CONSTRAINT `fk_CertificadoEnsinoMedio_Candidato1`
    FOREIGN KEY (`Candidato_IdCandidato`)
    REFERENCES `bd_enem_2015`.`Candidato` (`IdCandidato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)

-- -----------------------------------------------------
-- Table `bd_enem_2015`.`Inscricao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_enem_2015`.`Inscricao` (
  `IdNumInscri` INT NOT NULL,
  `AnoDoEnem` DATE NULL,
  `IndicUnidHosp` VARCHAR(45) NULL,
  `IndicTreinero` VARCHAR(45) NULL,
  `UnidadeFederativa_IdUF` INT NOT NULL,
  `Candidato_IdCandidato` INT NOT NULL,
  `Municipio_IdMunic` INT NOT NULL,
  PRIMARY KEY (`IdNumInscri`),
  INDEX `fk_Inscricao_UnidadeFederativa1_idx` (`UnidadeFederativa_IdUF` ASC),
  INDEX `fk_Inscricao_Candidato1_idx` (`Candidato_IdCandidato` ASC),
  INDEX `fk_Inscricao_Municipio1_idx` (`Municipio_IdMunic` ASC),
  CONSTRAINT `fk_Inscricao_UnidadeFederativa1`
    FOREIGN KEY (`UnidadeFederativa_IdUF`)
    REFERENCES `bd_enem_2015`.`UnidadeFederativa` (`IdUF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inscricao_Candidato1`
    FOREIGN KEY (`Candidato_IdCandidato`)
    REFERENCES `bd_enem_2015`.`Candidato` (`IdCandidato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inscricao_Municipio1`
    FOREIGN KEY (`Municipio_IdMunic`)
    REFERENCES `bd_enem_2015`.`Municipio` (`IdMunic`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)

-- -----------------------------------------------------
-- Table `bd_enem_2015`.`TipoPergunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_enem_2015`.`TipoPergunta` (
  `IdTipoPergunta` INT NOT NULL,
  `Pergunta` VARCHAR(45) NULL,
  PRIMARY KEY (`IdTipoPergunta`))

-- -----------------------------------------------------
-- Table `bd_enem_2015`.`QuestaoEstudoSocioeconomico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_enem_2015`.`QuestaoEstudoSocioeconomico` (
  `IdQuestao` INT NOT NULL,
  `Resposta` VARCHAR(45) NULL,
  `TipoPergunta_IdTipoPergunta` INT NOT NULL,
  `Candidato_IdCandidato` INT NOT NULL,
  PRIMARY KEY (`IdQuestao`, `Candidato_IdCandidato`),
  INDEX `fk_QuestaoEstudoSocioeconomico_TipoPergunta1_idx` (`TipoPergunta_IdTipoPergunta` ASC),
  INDEX `fk_QuestaoEstudoSocioeconomico_Candidato1_idx` (`Candidato_IdCandidato` ASC),
  CONSTRAINT `fk_QuestaoEstudoSocioeconomico_TipoPergunta1`
    FOREIGN KEY (`TipoPergunta_IdTipoPergunta`)
    REFERENCES `bd_enem_2015`.`TipoPergunta` (`IdTipoPergunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_QuestaoEstudoSocioeconomico_Candidato1`
    FOREIGN KEY (`Candidato_IdCandidato`)
    REFERENCES `bd_enem_2015`.`Candidato` (`IdCandidato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)

-- -----------------------------------------------------
-- Table `bd_enem_2015`.`NecessidadeEspecial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_enem_2015`.`NecessidadeEspecial` (
  `IdTipoNecess` INT NOT NULL,
  `NomeNecess` VARCHAR(45) NULL,
  PRIMARY KEY (`IdTipoNecess`))

-- -----------------------------------------------------
-- Table `bd_enem_2015`.`AtendimentoEspecial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_enem_2015`.`AtendimentoEspecial` (
  `IdTipoAtend` INT NOT NULL,
  `NomeAtendEsp` VARCHAR(45) NULL,
  PRIMARY KEY (`IdTipoAtend`))

-- -----------------------------------------------------
-- Table `bd_enem_2015`.`TipoProva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_enem_2015`.`TipoProva` (
  `IdProva` INT NOT NULL,
  `AreaDeConhec` VARCHAR(45) NULL,
  PRIMARY KEY (`IdProva`))

-- -----------------------------------------------------
-- Table `bd_enem_2015`.`Prova`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_enem_2015`.`Prova` (
  `IdProva` INT NOT NULL,
  `VetorResp` VARCHAR(45) NULL,
  `VetorGab` VARCHAR(45) NULL,
  `TipoLingua` VARCHAR(45) NULL,
  `Nota` INT NULL,
  `Presença` VARCHAR(45) NULL,
  `TipoProva_IdProva` INT NOT NULL,
  `UnidadeFederativa_IdUF` INT NOT NULL,
  `Municipio_IdMunic` INT NOT NULL,
  `Candidato_IdCandidato` INT NOT NULL,
  PRIMARY KEY (`IdProva`),
  INDEX `fk_Prova_TipoProva1_idx` (`TipoProva_IdProva` ASC),
  INDEX `fk_Prova_UnidadeFederativa1_idx` (`UnidadeFederativa_IdUF` ASC),
  INDEX `fk_Prova_Municipio1_idx` (`Municipio_IdMunic` ASC),
  INDEX `fk_Prova_Candidato1_idx` (`Candidato_IdCandidato` ASC),
  CONSTRAINT `fk_Prova_TipoProva1`
    FOREIGN KEY (`TipoProva_IdProva`)
    REFERENCES `bd_enem_2015`.`TipoProva` (`IdProva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prova_UnidadeFederativa1`
    FOREIGN KEY (`UnidadeFederativa_IdUF`)
    REFERENCES `bd_enem_2015`.`UnidadeFederativa` (`IdUF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prova_Municipio1`
    FOREIGN KEY (`Municipio_IdMunic`)
    REFERENCES `bd_enem_2015`.`Municipio` (`IdMunic`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prova_Candidato1`
    FOREIGN KEY (`Candidato_IdCandidato`)
    REFERENCES `bd_enem_2015`.`Candidato` (`IdCandidato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)

-- -----------------------------------------------------
-- Table `bd_enem_2015`.`Candidato_has_NecessidadeEspecial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_enem_2015`.`Candidato_has_NecessidadeEspecial` (
  `Candidato_IdCandidato` INT NULL,
  `NecessidadeEspecial_IdTipoNecess` INT NULL,
  PRIMARY KEY (`Candidato_IdCandidato`, `NecessidadeEspecial_IdTipoNecess`),
  INDEX `fk_Candidato_has_NecessidadeEspecial_NecessidadeEspecial1_idx` (`NecessidadeEspecial_IdTipoNecess` ASC),
  INDEX `fk_Candidato_has_NecessidadeEspecial_Candidato1_idx` (`Candidato_IdCandidato` ASC),
  CONSTRAINT `fk_Candidato_has_NecessidadeEspecial_Candidato1`
    FOREIGN KEY (`Candidato_IdCandidato`)
    REFERENCES `bd_enem_2015`.`Candidato` (`IdCandidato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Candidato_has_NecessidadeEspecial_NecessidadeEspecial1`
    FOREIGN KEY (`NecessidadeEspecial_IdTipoNecess`)
    REFERENCES `bd_enem_2015`.`NecessidadeEspecial` (`IdTipoNecess`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)

-- -----------------------------------------------------
-- Table `bd_enem_2015`.`Candidato_has_AtendimentoEspecial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_enem_2015`.`Candidato_has_AtendimentoEspecial` (
  `Candidato_IdCandidato` INT NULL,
  `AtendimentoEspecial_IdTipoAtend` INT NOT NULL,
  PRIMARY KEY (`Candidato_IdCandidato`, `AtendimentoEspecial_IdTipoAtend`),
  INDEX `fk_Candidato_has_AtendimentoEspecial_AtendimentoEspecial1_idx` (`AtendimentoEspecial_IdTipoAtend` ASC),
  INDEX `fk_Candidato_has_AtendimentoEspecial_Candidato1_idx` (`Candidato_IdCandidato` ASC),
  CONSTRAINT `fk_Candidato_has_AtendimentoEspecial_Candidato1`
    FOREIGN KEY (`Candidato_IdCandidato`)
    REFERENCES `bd_enem_2015`.`Candidato` (`IdCandidato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Candidato_has_AtendimentoEspecial_AtendimentoEspecial1`
    FOREIGN KEY (`AtendimentoEspecial_IdTipoAtend`)
    REFERENCES `bd_enem_2015`.`AtendimentoEspecial` (`IdTipoAtend`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
